package hash

const fileTpl = `// Code generated by protoc-gen-ext. DO NOT EDIT.
// source: {{ .InputPath }}

package {{ pkg . }}

import (
	"errors"
	"encoding/binary"
	"fmt"
	"hash"
	"hash/fnv"
	"strconv"

	"github.com/solo-io/protoc-gen-ext/pkg/hasher/hashstructure"
	safe_hasher "github.com/solo-io/protoc-gen-ext/pkg/hasher"

	{{ range $path, $pkg := enumPackages (externalEnums .) }}
		{{ $pkg }} "{{ $path }}"
	{{ end }}
)

// ensure the imports are used
var (
	_ = errors.New("")
	_ = fmt.Print
	_ = binary.LittleEndian
	_ = new(hash.Hash64)
	_ = fnv.New64
	_ = hashstructure.Hash
	_ = new(safe_hasher.SafeHasher)

	{{ range (externalEnums .) }}
		_ = {{ pkg . }}.{{ name . }}(0)
	{{ end }}
)

{{ range .AllMessages }}
	{{ template "msg" . }}
{{ end }}
`
