package golang

const fileTpl = `// Code generated by protoc-gen-ext. DO NOT EDIT.
// source: {{ .InputPath }}

package {{ pkg . }}

import (
	"errors"
	"encoding/binary"
	"fmt"
	"hash"
	"hash/fnv"

	"github.com/golang/protobuf/ptypes"
	"github.com/mitchellh/hashstructure"

	{{ range $path, $pkg := enumPackages (externalEnums .) }}
		{{ $pkg }} "{{ $path }}"
	{{ end }}
)

// ensure the imports are used
var (
	_ = errors.New("")
	_ = fmt.Print

	{{ range (externalEnums .) }}
		_ = {{ pkg . }}.{{ name . }}(0)
	{{ end }}
)

{{ range .AllMessages }}
	{{ template "msg" . }}
{{ end }}
`
