name: CI
on: pull_request
jobs:
  unit_tests:
    name: unit tests
    runs-on: ubuntu-22.04
    steps:
    - name: Cancel Previous Actions
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"
      id: go
    - name: Test
      run: make install-go-tools run-tests
